---
- import_tasks: pre_tasks.yml

- name: 'Downloading Java JDK package from: {{ jdk_package_url }}'
  get_url:
    url: '{{ jdk_package_url }}'
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: '/tmp/{{ jdk_package_name }}'
    checksum: '{{ jdk_package_checksum | default(omit) }}'
  when: (target.stat.exists == False) or
        (alternative.stat.islnk is not defined)
  tags:
    - oracle_java

- name: Install Java JDK package
  yum:
    name: '/tmp/{{ jdk_package_name }}'
    state: present
  when: (target.stat.exists == False) or
        (alternative.stat.islnk is not defined)
  tags:
    - oracle_java

- name: Set the correct Java JDK package
  alternatives:
    link: /usr/bin/java
    name: java
    path: '{{ target.stat.path }}'
    priority: 200000
  when: ( alternative.stat.lnk_target|string() != target.stat.path|string() )
  tags:
    - oracle_java

- import_tasks: post_tasks.yml
