---
- import_tasks: pre_tasks.yml

- name: 'Downloading Java JDK package from: {{ jdk_package_url }}'
  get_url:
    url: '{{ jdk_package_url }}'
    headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
    dest: '/tmp/{{ jdk_package_name }}'
    checksum: '{{ jdk_package_checksum | default(omit) }}'
  when: (target.stat.exists == False) or
        (alternative.stat.islnk is not defined)
  tags:
    - oracle_java

- name: 'Unpacking Java JDK at: {{ jdk_dir_path }}'
  unarchive:
    src: /tmp/{{ jdk_package_name }}
    dest: '{{ jdk_dir_path }}'
    copy: no
    owner: root
    group: root
  when:
    - target.stat.exists == False
  tags:
    - oracle_java

- name: Find JDK Binaries
  find:
    paths: "{{ jdk_home }}/bin"
    file_type: file
  register: binaries

- name: Installing Java alternatives
  alternatives:
    name: '{{ item.path | basename }}'
    link: '/usr/bin/{{ item.path | basename }}'
    path: '{{ item.path }}'
    priority: 200000
  with_items:
    - '{{ binaries.files | default([]) }}'
  tags:
    - oracle_java

- import_tasks: pre_tasks.yml
