---
- name: "Check if {{ jdk_home }}/bin/java exists"
  stat:
    path: '{{ jdk_home }}/bin/java'
  register: target
  tags:
    - oracle_java

- debug:
    msg: '{{ jdk_home }}/bin/java does exist!'
  when:
    - target.stat.exists == True
    - target.stat.isreg
  tags:
    - oracle_java

- name: Set fact oracle_java_8_installed
  set_fact:
    oracle_java_8_installed: true
  when:
    - target.stat.exists == True
    - target.stat.isreg
