---
- name: "Check if {{ jdk_home }}/jre/bin/java exists"
  stat:
    path: '{{ jdk_home }}/jre/bin/java'
  register: target
  tags:
    - oracle_java

- debug:
    msg: '{{ jdk_home }}/jre/bin/java does exist!'
  when:
    - target.stat.exists == True
    - target.stat.isreg
  tags:
    - oracle_java

- name: Set fact oracle_java_8_installed
  set_fact:
    oracle_java_8_installed: true
  when:
    - target.stat.exists == True
    - target.stat.isreg

- debug:
    msg: "/etc/alternatives/java is defined and points to {{ alternative.stat.lnk_target }}"
  when:
    - alternative.stat.islnk is defined
    - alternative.stat.islnk
  tags:
    - oracle_java
